#!/bin/sh

export HOME="/root"
export SHELL="/bin/bash"
export LANG=en_US.UTF-8
export PATH="/bin:/usr/bin:/usr/sbin:/sbin:/bin:/usr/local/bin:/usr/local/sbin"
export XDG_RUNTIME_DIR="/run/user/0"

mkdir -p /tmp/.X11-unix
mkdir -p /tmp/.ICE-unix
mkdir -p $HOME/.config/dconf
mkdir -p /run/dbus
mkdir -p /var/lib/dbus
mkdir -p $XDG_RUNTIME_DIR

chmod 01777 /tmp/.X11-unix
chmod 0777 /tmp/.ICE-unix
chmod 0700 $XDG_RUNTIME_DIR

dbus-daemon --system --fork
dbus-uuidgen --ensure

udevd &

while [ ! -e "/run/udev/control" ]; do
    sleep 0.1
done

udevadm settle

exec runuser -l root -c "/usr/lib/aether/start-xfce4-session"
