#!/bin/sh

export HOME="/root"
export SHELL="/bin/bash"
export XDG_SESSION_TYPE="wayland"
export XDG_CONFIG_DIRS="/etc/xdg"
export XDG_RUNTIME_DIR="/run/user/0"
export NO_AT_BRIDGE=1
export LC_ALL=en_US.utf8
export PATH="/usr/local/sbin:/usr/local/bin:/bin:/usr/bin:/sbin:$HOME/.local/bin:$HOME/.local/bin"
export LIBGL_ALWAYS_SOFTWARE=1
export WLR_RENDERER=pixman
export WLR_RENDERER_ALLOW_SOFTWARE=1
export SDL_VIDEODRIVER=x11
export SDL_AUDIODRIVER=dummy

mkdir -p /tmp/.X11-unix
mkdir -p /tmp/.ICE-unix
mkdir -p $HOME/.config/dconf
mkdir -p /run/dbus
mkdir -p /var/lib/dbus
mkdir -p $XDG_RUNTIME_DIR

chmod 0777 /tmp/.X11-unix
chmod 0777 /tmp/.ICE-unix
chmod 0700 $XDG_RUNTIME_DIR

dbus-daemon --system --fork
dbus-uuidgen --ensure

udevd &

exec dbus-run-session seatd-launch -- weston --xwayland
