#! /bin/sh

name=fontconfig
version=2.16.2
revision=1
git_url="https://gitlab.freedesktop.org/fontconfig/fontconfig.git"
commit=72b9a48f57de6204d99ce1c217b5609ee92ece9b
imagedeps="build-essential"
hostdeps="gcc pkg-config gperf"
deps="core-libs freetype2 libexpat libxml2"

configure() {
    meson_configure
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
