#! /bin/sh

name=fontconfig
version=2.16.2
revision=1
git_url="https://gitlab.freedesktop.org/fontconfig/fontconfig.git"
commit=8f169b6a9c6be7e8f1fa3480d93b33befa6bee3f
imagedeps="gperf"
hostdeps="gcc pkg-config"
deps="core-libs freetype2 libexpat libxml2"

configure() {
    meson_configure \
        -Dxml-backend=libxml2
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    rm -v "${dest_dir}${prefix}"/lib/*.a

    post_package_strip
}
