#! /bin/sh

name=kmscon
skip_pkg_check=yes
version=14.0.0git
revision=1
git_url="https://github.com/Aetf/kmscon.git"
commit=b90eab1f75510df7a34388d821ea15cfc6414eb0
imagedeps="build-essential pkg-config libwayland-dev"
hostdeps="gcc pkg-config"
deps="core-libs linux-headers libxkbcommon libdrm libudev libtsm pango"

configure() {
    meson_configure \
        -Dextra_debug=true \
        -Dtests=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild
}
