#! /bin/sh

name=libxkbcommon
version=1.9.2
revision=1
git_url="https://github.com/xkbcommon/libxkbcommon.git"
commit=e9fd95a5a3671fdda4e9dd16ae8b060869296180
imagedeps="libwayland-bin pkg-config"
hostdeps="gcc pkg-config"
deps="core-libs libxcb libxml2 xkeyboard-config wayland wayland-protocols"

configure() {
    meson_configure \
        -Dxkb-config-root="$prefix"/share/X11/xkb
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    mkdir -p "${dest_dir}${prefix}/share/X11/xkb"
    touch "${dest_dir}${prefix}/share/X11/xkb/.keep"

    post_package_strip
}
