#! /bin/sh

name=linux
version=6.14.6
revision=1
tarball_url="https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-${version}.tar.xz"
tarball_blake2b="dedcadc0b7506f620da3ac849446539e83d694f0955d5417e063b6680d53ef8993eeef40562ae8dae9249a21bea9746093f8873a360dd74f6b139fbafdd7b9ac"
revision=1
imagedeps="bc build-essential cpio dwarves kmod libelf-dev libncurses5-dev libssl-dev dracut busybox"
hostdeps="gcc"

build() {
    cp -rp "${source_dir}"/. ./
}
