#! /bin/sh

name=weston
skip_pkg_check=yes
version=14.0.90git
revision=1
git_url="https://gitlab.freedesktop.org/wayland/weston.git"
commit=015b3b4d4c05da44a22349ea6e651d1a8f678c59
imagedeps="build-essential pkg-config libwayland-dev"
hostdeps="gcc pkg-config"
deps="core-libs libxkbcommon wayland wayland-protocols pixman libinput libdrm cairo pam libxcursor lcms seatd libdisplay-info"

configure() {
    CFLAGS="$TARGET_CFLAGS -Wno-implicit-function-declaration" \
    CXXFLAGS="$TARGET_CXXFLAGS -Wno-implicit-function-declaration" \
    LDFLAGS="$TARGET_LDFLAGS" \
    meson_configure_noflags \
        --buildtype=debug \
        -Dbackend-default=drm \
        -Dbackend-drm-screencast-vaapi=false \
        -Dbackend-x11=false \
        -Dbackend-rdp=false \
        -Dbackend-vnc=false \
        -Dbackend-pipewire=false \
        -Ddemo-clients=false \
        -Dsystemd=false \
        -Dremoting=false \
        -Drenderer-gl=false \
        -Dimage-jpeg=false \
        -Dimage-webp=false \
        -Dpipewire=false \
        -Dsimple-clients=[] \
    	-Dtest-skip-is-failure=false \
        -Dtest-junit-xml=false \
        -Dxwayland=false
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild
}
