#!/bin/sh

/bin/mkdir -p /dev/
/bin/mount -t devtmpfs devtmpfs /dev

/bin/echo "Aether-OS init script is running..."

/bin/mkdir -p /mnt/

root_mounted=0

for path in /dev/*; do
    if [[ $path == *"part"* ]]; then
        /bin/echo "Trying mount $path as root"
        /bin/mount -t ext $path /mnt/
        if [ $? -eq 0 ]; then
            root_mounted=1
            break
        fi
    fi
done

if [ $root_mounted -eq 0 ]; then
    /bin/echo "Mount root failed..."
    exec /bin/sh
fi

/bin/umount /dev

/bin/mkdir -p /mnt/dev/
/bin/mkdir -p /mnt/proc/
/bin/mkdir -p /mnt/sys/
/bin/mkdir -p /mnt/run/
/bin/mkdir -p /mnt/tmp/

/bin/mount -t devtmpfs devtmpfs /mnt/dev
/bin/mount -t proc proc /mnt/proc
/bin/mount -t sysfs sysfs /mnt/sys
/bin/mount -t cgroup2 cgroup2 /mnt/sys/fs/cgroup
/bin/mount -t tmpfs tmpfs /mnt/run
/bin/mount -t tmpfs tmpfs /mnt/tmp

/bin/echo "Ready to switch root..."

exec /sbin/switch_root /mnt/ /usr/lib/aether/init
