#!/bin/sh

/bin/mkdir -p /dev
/bin/mount -t devtmpfs devtmpfs /dev

/bin/echo "Aether-OS init script is running..."

root_mounted=0

for path in /dev/*; do
    if [[ $path == *"part"* ]]; then
        /bin/echo "Trying mount $path as root"
        /bin/mount -t ext $path /mnt/
        if [ $? -eq 0 ]; then
            root_mounted=1
            break
        fi
    fi
done

/bin/umount /dev/

if [ $root_mounted -eq 0 ]; then
    /bin/echo "Mount root failed..."
    exit 1
fi

/bin/echo "Ready to switch root..."

exec /sbin/switch_root /mnt/ /sbin/init
