#!/usr/bin/env sh
# Generate a C header containing a raw P-256 public key point.
#
# Usage:
#   sh kernel/scripts/convert_ecc_pubkey.sh <public_key.pem> <output_header> [array_name]
#
# The generated array contains the uncompressed SEC1 public point:
#   0x04 || X(32 bytes) || Y(32 bytes)

set -eu

if [ "$#" -lt 2 ] || [ "$#" -gt 3 ]; then
    echo "Usage: $0 <public_key.pem> <output_header> [array_name]" >&2
    exit 1
fi

INPUT_PEM=$1
OUTPUT_HEADER=$2
ARRAY_NAME=${3:-naos_signing_key_pub}

if ! command -v openssl >/dev/null 2>&1; then
    echo "Error: openssl command not found." >&2
    exit 1
fi

if ! command -v od >/dev/null 2>&1; then
    echo "Error: od command not found." >&2
    exit 1
fi

if [ ! -f "$INPUT_PEM" ]; then
    echo "Error: public key not found: $INPUT_PEM" >&2
    exit 1
fi

if ! printf '%s\n' "$ARRAY_NAME" | grep -Eq '^[A-Za-z_][A-Za-z0-9_]*$'; then
    echo "Error: invalid C array name: $ARRAY_NAME" >&2
    exit 1
fi

if ! openssl ec -pubin -in "$INPUT_PEM" -noout -text 2>/dev/null |
    grep -Eq 'ASN1 OID:[[:space:]]*(prime256v1|secp256r1)|NIST CURVE:[[:space:]]*P-256'; then
    echo "Error: expected a P-256 public key: $INPUT_PEM" >&2
    exit 1
fi

OUT_DIR=$(dirname "$OUTPUT_HEADER")
TMP_KEY=$(mktemp "${TMPDIR:-/tmp}/naos-pubkey.XXXXXX")
trap 'rm -f "$TMP_KEY"' EXIT INT TERM

mkdir -p "$OUT_DIR"

# For prime256v1/secp256r1 SubjectPublicKeyInfo DER, the last 65 bytes are the
# uncompressed EC point. Validate the shape so malformed or wrong-curve input is
# caught before generating a header.
if ! openssl ec -pubin -in "$INPUT_PEM" -outform DER 2>/dev/null | tail -c 65 >"$TMP_KEY"; then
    echo "Error: failed to extract EC public key from $INPUT_PEM" >&2
    exit 1
fi

KEY_LEN=$(wc -c <"$TMP_KEY" | tr -d ' ')
FIRST_BYTE=$(od -An -tx1 -N1 "$TMP_KEY" | tr -d ' \n')

if [ "$KEY_LEN" != "65" ] || [ "$FIRST_BYTE" != "04" ]; then
    echo "Error: expected an uncompressed P-256 public key point (65 bytes)." >&2
    exit 1
fi

{
    echo "/*"
    echo " * Generated by kernel/scripts/convert_ecc_pubkey.sh."
    echo " * Source: $INPUT_PEM"
    echo " */"
    echo "#pragma once"
    echo
    echo "#ifndef ASM_FILE"
    echo "#define ${ARRAY_NAME}_LEN 65"
    echo
    echo "static const unsigned char ${ARRAY_NAME}[] = {"
    od -An -tx1 -v "$TMP_KEY" | awk '
        {
            for (i = 1; i <= NF; i++) {
                bytes[++n] = $i
            }
        }
        END {
            for (i = 1; i <= n; i++) {
                if ((i - 1) % 16 == 0) {
                    printf "    "
                }
                printf "0x%s", bytes[i]
                if (i < n) {
                    printf ", "
                }
                if (i % 16 == 0 || i == n) {
                    printf "\n"
                }
            }
        }'
    echo "};"
    echo "#endif"
} >"$OUTPUT_HEADER"

echo "Generated $OUTPUT_HEADER from $INPUT_PEM"
