#include <libs/keys.h>

static const uint8_t evdev_base_table[89] = {
    0,
    KEY_ESC,
    KEY_1,
    KEY_2,
    KEY_3,
    KEY_4,
    KEY_5,
    KEY_6,
    KEY_7,
    KEY_8,
    KEY_9,
    KEY_0,
    KEY_MINUS,
    KEY_EQUAL,
    KEY_BACKSPACE,
    KEY_TAB,
    KEY_Q,
    KEY_W,
    KEY_E,
    KEY_R,
    KEY_T,
    KEY_Y,
    KEY_U,
    KEY_I,
    KEY_O,
    KEY_P,
    KEY_LEFTBRACE,
    KEY_RIGHTBRACE,
    KEY_ENTER,
    KEY_LEFTCTRL,
    KEY_A,
    KEY_S,
    KEY_D,
    KEY_F,
    KEY_G,
    KEY_H,
    KEY_J,
    KEY_K,
    KEY_L,
    KEY_SEMICOLON,
    KEY_APOSTROPHE,
    KEY_GRAVE,
    KEY_LEFTSHIFT,
    KEY_BACKSLASH,
    KEY_Z,
    KEY_X,
    KEY_C,
    KEY_V,
    KEY_B,
    KEY_N,
    KEY_M,
    KEY_COMMA,
    KEY_DOT,
    KEY_SLASH,
    KEY_RIGHTSHIFT,
    KEY_KPASTERISK,
    KEY_LEFTALT,
    KEY_SPACE,
    KEY_CAPSLOCK,
    KEY_F1,
    KEY_F2,
    KEY_F3,
    KEY_F4,
    KEY_F5,
    KEY_F6,
    KEY_F7,
    KEY_F8,
    KEY_F9,
    KEY_F10,
    KEY_NUMLOCK,
    KEY_SCROLLLOCK,
    KEY_KP7,
    KEY_KP8,
    KEY_KP9,
    KEY_KPMINUS,
    KEY_KP4,
    KEY_KP5,
    KEY_KP6,
    KEY_KPPLUS,
    KEY_KP1,
    KEY_KP2,
    KEY_KP3,
    KEY_KP0,
    KEY_KPDOT,
    0,
    0,
    0,
    KEY_F11,
    KEY_F12,
};

static const uint8_t evdev_ext_table[128] = {
    [0x1C] = KEY_KPENTER,  [0x1D] = KEY_RIGHTCTRL, [0x35] = KEY_KPSLASH,
    [0x37] = KEY_SYSRQ,    [0x38] = KEY_RIGHTALT,  [0x47] = KEY_HOME,
    [0x48] = KEY_UP,       [0x49] = KEY_PAGEUP,    [0x4B] = KEY_LEFT,
    [0x4D] = KEY_RIGHT,    [0x4F] = KEY_END,       [0x50] = KEY_DOWN,
    [0x51] = KEY_PAGEDOWN, [0x52] = KEY_INSERT,    [0x53] = KEY_DELETE,
    [0x5B] = KEY_LEFTMETA, [0x5C] = KEY_RIGHTMETA, [0x5D] = KEY_MENU,
};

uint16_t evdev_code_from_set1_scancode(uint8_t scan_code, bool is_extended) {
    if (is_extended) {
        if (scan_code < sizeof(evdev_ext_table)) {
            return evdev_ext_table[scan_code];
        }
    } else {
        if (scan_code < sizeof(evdev_base_table)) {
            return evdev_base_table[scan_code];
        }
    }

    return 0;
}
