#pragma once

#define SERIAL_DEBUG 0

#define LIMINE_API_REVISION 3

#define DEFAULT_PAGE_SIZE 4096UL

#define MAX_CPU_NUM 256
#define MAX_IO_CPU_NUM 8
#define STACK_SIZE 32768UL

#define BUILD_VERSION "0.69.2"

#define MAX_TASK_NUM 4096
#define MAX_CONTINUE_NULL_TASKS 16
#define SCHED_HZ 200
