#pragma once

#define SERIAL_DEBUG 1
#define DEFAULT_TTY "ttyS0"

#define LIMINE_API_REVISION 3

#define DEFAULT_PAGE_SIZE 4096UL

#define MAX_CPU_NUM 128
#define MAX_IO_CPU_NUM 4
#define STACK_SIZE (256 * 1024)

#define BUILD_VERSION "0.10.0"

#define MAX_TASK_NUM 4096
#define MAX_CONTINUE_NULL_TASKS 16
#define SCHED_HZ 100
